const esc = (value = "") => String(value).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);

const STYLE = `*{box-sizing:border-box}body{margin:0;font:16px/1.5 system-ui,-apple-system,Segoe UI,sans-serif;background:#F4F6FA;color:#0B1A33}main{max-width:880px;margin:0 auto;padding:clamp(20px,5vw,56px) 20px}.card{background:#fff;border:1px solid #dfe6f1;border-radius:18px;padding:28px}h1{margin:0 0 6px;font-size:clamp(26px,5vw,34px);letter-spacing:-.02em}p{color:#5b6b85}.btn{border:0;border-radius:12px;padding:12px 18px;font-weight:700;cursor:pointer;background:#0A2347;color:#fff;min-height:44px}.btn[disabled]{opacity:.5;cursor:not-allowed}.btn.y{background:#F3BE34;color:#1a1405}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:22px 0}.stat{background:#F4F6FA;border-radius:14px;padding:14px}.stat b{display:block;font-size:30px;line-height:1;margin-top:4px;font-variant-numeric:tabular-nums}.stat small{color:#5b6b85;font-size:12px;text-transform:uppercase;letter-spacing:.06em}.err{color:#a82f27;min-height:1.4em}code{background:#eef3fa;padding:2px 6px;border-radius:6px}.row{display:flex;gap:10px;flex-wrap:wrap;align-items:center;justify-content:space-between}`;


export function adminShell({ state, clientId = "", csrf = "", missing = [], setup = false }) {
  const body = state === "unconfigured"
    ? `<div class="card"><h1>Radar Admin sin configurar</h1><p>El panel permanece cerrado hasta configurar estas variables de entorno en Vercel (solo se muestran los nombres):</p><ul>${missing.map((name) => `<li><code>${esc(name)}</code></li>`).join("")}</ul></div>`
    : state === "login"
      ? `<div class="card"><h1>IvanImports Radar · Admin</h1>${setup ? "<p><b>Modo de alta inicial.</b> Todavía no hay ninguna cuenta autorizada. Inicia sesión con tu cuenta de Google para ver tu identificador y autorizarla en Vercel. No se crea ninguna sesión ni se guarda nada.</p>" : "<p>Acceso privado. Solo la cuenta de Google autorizada puede entrar.</p>"}<div id="g-button" style="min-height:44px;margin:18px 0"></div><p class="err" id="err" role="alert"></p></div>`
      : `<div id="ax" class="ax" aria-live="polite">Cargando…</div>`;
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="referrer" content="${state === "login" ? "strict-origin-when-cross-origin" : "no-referrer"}"><title>Radar Admin</title><style>${STYLE}</style>${state === "panel" ? '<link rel="stylesheet" href="/assets/radar/app.css"><link rel="stylesheet" href="/assets/radar/admin.css">' : ""}${state === "login" ? '<script src="https://accounts.google.com/gsi/client" async defer></script>' : ""}</head><body data-state="${esc(state)}" data-setup="${setup ? "1" : ""}" data-client-id="${esc(clientId)}" data-csrf="${esc(csrf)}"><main class="${state === 'panel' ? 'ax-main' : ''}">${body}</main>${state !== "unconfigured" ? '<script type="module" src="/assets/radar/admin.js"></script>' : ""}</body></html>`;
}
